import { prisma } from "@/lib/prisma";
import { RuleAction } from "./automation.types";
import { TaskDomainService } from "../task/task.service";
import { eventBus } from "../events/event-bus";
import { TaskStatus, TaskPriority, ProjectRole } from "@prisma/client";

export interface ActionExecutionContext {
  workspaceId: string;
  projectId?: string | null;
  ruleId: string;
  eventId: string;
  eventPayload: any;
  task?: any;
}

export class AutomationActions {
  /**
   * Executes a single automation action via authoritative domain services.
   * NEVER mutates Prisma task records directly.
   */
  static async execute(action: RuleAction, context: ActionExecutionContext): Promise<{ success: boolean; error?: string }> {
    const actorId = "SYSTEM";
    const taskId =
      context.task?.id ||
      context.eventPayload?.taskId ||
      (context.eventPayload?.taskTitle ? context.eventPayload?.taskId : null);

    switch (action.type) {
      case "SET_STATUS": {
        if (!taskId) return { success: false, error: "Task ID missing for SET_STATUS action" };
        const targetStatus = action.payload.status as TaskStatus;
        if (!targetStatus) return { success: false, error: "Target status missing" };

        await TaskDomainService.changeStatus(actorId, taskId, targetStatus);
        return { success: true };
      }

      case "SET_PRIORITY": {
        if (!taskId) return { success: false, error: "Task ID missing for SET_PRIORITY action" };
        const targetPriority = action.payload.priority as TaskPriority;
        if (!targetPriority) return { success: false, error: "Target priority missing" };

        await TaskDomainService.changePriority(actorId, taskId, targetPriority);
        return { success: true };
      }

      case "ASSIGN_TASK": {
        if (!taskId) return { success: false, error: "Task ID missing for ASSIGN_TASK action" };
        const assigneeId = action.payload.assigneeId;
        if (!assigneeId) return { success: false, error: "Assignee ID missing" };

        await TaskDomainService.assignTask(actorId, taskId, assigneeId);
        return { success: true };
      }

      case "UNASSIGN_TASK": {
        if (!taskId) return { success: false, error: "Task ID missing for UNASSIGN_TASK action" };

        await TaskDomainService.unassignTask(actorId, taskId);
        return { success: true };
      }

      case "CREATE_NOTIFICATION": {
        let recipientUserId = action.payload.userId || action.payload.specificUserId;

        // Dynamic recipient resolution
        if (!recipientUserId && action.payload.recipientType) {
          if (action.payload.recipientType === "ASSIGNEE") {
            recipientUserId = context.task?.assigneeId || context.eventPayload?.assigneeId;
          } else if (action.payload.recipientType === "CREATOR") {
            recipientUserId = context.task?.creatorId || context.eventPayload?.creatorId;
          } else if (action.payload.recipientType === "LEAD") {
            const resolvedProjId = context.projectId || context.task?.projectId || context.eventPayload?.projectId;
            if (resolvedProjId) {
              const leadMember = await prisma.projectMember.findFirst({
                where: { projectId: resolvedProjId, role: ProjectRole.LEAD },
                select: { userId: true },
              });
              recipientUserId = leadMember?.userId;
            }
          }
        }

        if (!recipientUserId) {
          return { success: false, error: "Could not resolve recipient for notification action" };
        }

        const title = action.payload.title || "Automation Notification";
        const description = action.payload.description || "Notification generated by workflow rule.";

        const notif = await prisma.notification.create({
          data: {
            workspaceId: context.workspaceId,
            userId: recipientUserId,
            title,
            description,
            type: "SYSTEM",
            link: taskId ? `/tasks?selected=${taskId}` : undefined,
          },
        });

        await eventBus.emit({
          type: "NOTIFICATION_CREATED",
          workspaceId: context.workspaceId,
          projectId: context.projectId || undefined,
          actorId: "SYSTEM",
          payload: {
            notificationId: notif.id,
            userId: notif.userId,
            title: notif.title,
            description: notif.description,
            type: notif.type,
            link: notif.link,
          },
        });

        return { success: true };
      }

      case "ADD_COMMENT": {
        if (!taskId) return { success: false, error: "Task ID missing for ADD_COMMENT action" };
        const content = action.payload.content || "Automated system update.";

        // Resolve author ID for comment: specific author or workspace owner
        let authorId = action.payload.authorId;
        if (!authorId) {
          const ws = await prisma.workspace.findUnique({
            where: { id: context.workspaceId },
            select: { ownerId: true },
          });
          authorId = ws?.ownerId;
        }

        if (!authorId) {
          return { success: false, error: "Could not resolve author for automated comment" };
        }

        const task = await prisma.task.findUnique({
          where: { id: taskId },
          select: { id: true, title: true, projectId: true },
        });

        const comment = await prisma.taskComment.create({
          data: {
            taskId,
            authorId,
            content: `[Automation] ${content}`,
          },
        });

        await eventBus.emit({
          type: "COMMENT_CREATED",
          workspaceId: context.workspaceId,
          projectId: task?.projectId,
          actorId: "SYSTEM",
          payload: {
            commentId: comment.id,
            taskId,
            taskTitle: task?.title || "Task",
            content: comment.content,
            authorId,
          },
        });

        return { success: true };
      }

      default:
        return { success: false, error: `Unsupported action type: ${(action as any).type}` };
    }
  }
}
